version: '3.9'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - web-app
  web-app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - "postgre_db"
    env_file:
      - .env
  postgre_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: mihailabakumov
      POSTGRES_PASSWORD: 1599
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container_09
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
  redis:
    image: redis:latest
    ports:
      - 6378:6378

  celery:
    build: .
    command: python -m celery -A diplom worker -l info 
    volumes:
      - .:/app
    depends_on:
      - web-app
      - redis